# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.settlement_api import SettlementApi


class TestSettlementApi(unittest.TestCase):
    """SettlementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettlementApi()

    def tearDown(self) -> None:
        pass

    def test_settlement_delete(self) -> None:
        """Test case for settlement_delete

        """
        pass

    def test_settlement_get(self) -> None:
        """Test case for settlement_get

        """
        pass

    def test_settlement_patch(self) -> None:
        """Test case for settlement_patch

        """
        pass

    def test_settlement_post(self) -> None:
        """Test case for settlement_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
