# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.balance_api import BalanceApi


class TestBalanceApi(unittest.TestCase):
    """BalanceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BalanceApi()

    def tearDown(self) -> None:
        pass

    def test_balance_delete(self) -> None:
        """Test case for balance_delete

        """
        pass

    def test_balance_get(self) -> None:
        """Test case for balance_get

        """
        pass

    def test_balance_patch(self) -> None:
        """Test case for balance_patch

        """
        pass

    def test_balance_post(self) -> None:
        """Test case for balance_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
