# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.alembic_version_api import AlembicVersionApi


class TestAlembicVersionApi(unittest.TestCase):
    """AlembicVersionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlembicVersionApi()

    def tearDown(self) -> None:
        pass

    def test_alembic_version_delete(self) -> None:
        """Test case for alembic_version_delete

        """
        pass

    def test_alembic_version_get(self) -> None:
        """Test case for alembic_version_get

        """
        pass

    def test_alembic_version_patch(self) -> None:
        """Test case for alembic_version_patch

        """
        pass

    def test_alembic_version_post(self) -> None:
        """Test case for alembic_version_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
