# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.introspection_api import IntrospectionApi


class TestIntrospectionApi(unittest.TestCase):
    """IntrospectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IntrospectionApi()

    def tearDown(self) -> None:
        pass

    def test_root_get(self) -> None:
        """Test case for root_get

        OpenAPI description (this document)
        """
        pass


if __name__ == '__main__':
    unittest.main()
