# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.models.inventory import Inventory

class TestInventory(unittest.TestCase):
    """Inventory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Inventory:
        """Test Inventory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Inventory`
        """
        model = Inventory()
        if include_optional:
            return Inventory(
                dt = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                symbol = '',
                num_share = 56,
                id = 56
            )
        else:
            return Inventory(
                dt = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                symbol = '',
                num_share = 56,
                id = 56,
        )
        """

    def testInventory(self):
        """Test Inventory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
