# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.market_metadata_api import MarketMetadataApi


class TestMarketMetadataApi(unittest.TestCase):
    """MarketMetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MarketMetadataApi()

    def tearDown(self) -> None:
        pass

    def test_market_metadata_delete(self) -> None:
        """Test case for market_metadata_delete

        """
        pass

    def test_market_metadata_get(self) -> None:
        """Test case for market_metadata_get

        """
        pass

    def test_market_metadata_patch(self) -> None:
        """Test case for market_metadata_patch

        """
        pass

    def test_market_metadata_post(self) -> None:
        """Test case for market_metadata_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
