# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.models.kline import Kline

class TestKline(unittest.TestCase):
    """Kline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Kline:
        """Test Kline
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Kline`
        """
        model = Kline()
        if include_optional:
            return Kline(
                id = 56,
                symbol = '',
                dt = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                open = 1.337,
                high = 1.337,
                low = 1.337,
                close = 1.337,
                volume = 56
            )
        else:
            return Kline(
                id = 56,
                symbol = '',
                dt = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                open = 1.337,
                high = 1.337,
                low = 1.337,
                close = 1.337,
                volume = 56,
        )
        """

    def testKline(self):
        """Test Kline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
