# coding: utf-8

"""
    standard public schema

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 12.2.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from fugledata.api.kline_api import KlineApi


class TestKlineApi(unittest.TestCase):
    """KlineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = KlineApi()

    def tearDown(self) -> None:
        pass

    def test_kline_delete(self) -> None:
        """Test case for kline_delete

        """
        pass

    def test_kline_get(self) -> None:
        """Test case for kline_get

        """
        pass

    def test_kline_patch(self) -> None:
        """Test case for kline_patch

        """
        pass

    def test_kline_post(self) -> None:
        """Test case for kline_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
